const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1576845461000,
      duration: 7200000,
      id: '267317596',
      name: 'Pitch Club Developer Edition #47',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584039600000,
      local_date: '2020-03-12',
      local_time: '20:00',
      updated: 1576845613000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
        id: 25959917,
        name: 'Bar Ludwig II',
        lat: 48.12186813354492,
        lon: 11.58230972290039,
        repinned: true,
        address_1: 'Hochstraße 77',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1539021073000,
        name: 'Pitch Club Developer Edition München',
        id: 30141555,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Pitch-Club-Developer-Edition-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/267317596/',
      description: '<p>Softwareentwickler und IT-Professionals aufgepasst! Pitch Club veranstaltet am 12. März 2020 ab 17 Uhr in der Bar Ludwig II (Hochstraße 77, 81541 München) die “Pitch Club Developer Edition #47” in München. Hierfür suchen wir noch Entwickler und Projektmanager aus dem IT-Bereich, die an dem Event teilnehmen möchten.</p> <p>Beim Event treffen gestandene Unternehmen und Startups auf IT-Professionals, die es zu überzeugen gilt. Die Unternehmen pitchen ihr HR-Konzept, Jobs und Projekte und versuchen so, die Talente für sich zu gewinnen. Die Entwickler stellen zudem unbequeme Fragen und prüfen die Jobs auf Herz und Nieren. Am Ende müssen die Unternehmen in 1-on-1 Gesprächen nochmal alles geben, bei der alle Teilnehmer sich bei Speisen und Getränken austauschen und gegebenenfalls schon mit ihren zukünftigen Arbeitgebern in Kontakt treten können. Nach Abschluss der Veranstaltung geht das Event ab 20 Uhr in die öffentliche Afterwork Party über.</p> <p>Wenn Du an der kostenlosen Teilnahme (inklusive Snackbuffet, Softdrinks, Bier und Long Drinks) beim invite-only Event ab 17 Uhr interessiert bist, dann bewirb Dich unter:',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1581324523000,
      duration: 5400000,
      id: '268599428',
      name: 'First kick-off event',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582822800000,
      local_date: '2020-02-27',
      local_time: '18:00',
      updated: 1581324971000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 24,
      group: {
        created: 1573128374000,
        name: 'Microfrontends',
        id: 32986964,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Microfrontends',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Microfrontends/events/268599428/',
      description: '<p>Dear Microfrontend friends,<br/>The time has come to organize our first kick-off event! The idea is to have the first one, just as a small get-together event, where I would really love to meet as much of you as possible and to hear more about your microfrontend projects/ideas, but also would like to use the opportunity to talk about the next, real, full-scale meetup event.</p> <p>The location will attach later after I see how many people want to attend, and depending on the interest, it might be a restaurant or might find some other location where we can have more space, in case of bigger interest.</p> <p>Once again short agenda:<br/>- Getting to know each other<br/>- Sharing microfrontend projects/ideas<br/>- Planning next, full-scale, meetup event</p> <p>I\'m really excited and looking forward to meeting you all!!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1562151747000,
      duration: 169200000,
      id: '262837309',
      name: 'Campus Hackathon München 2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1587142800000,
      local_date: '2020-04-17',
      local_time: '19:00',
      updated: 1562151747000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      group: {
        created: 1501244830000,
        name: 'Tech_Hub München',
        id: 25186228,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Tech_Hub-Munchen',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Tech_Hub-Munchen/events/262837309/',
      description: '<p>At Campus Hackathon coders, creative developers and designers are working together intensively and under time-pressure hands-on projects. You have 24 hours to convert an idea into code. You already have some ideas? You want to use the tools and platforms you’re familiar with? No problem! The apps can be developed with the backends and frontend technologies you love. We’ll be providing healthy and tasty snacks and meals to keep your mind, body, soul balanced while hacking and you will be supported by experienced mentors of SAP, Finanz Informatik Solutions Plus and mindsquare. You can participate in a group or individually and we match you with another team.</p> <p>Beim Campus Hackathon hast Du 24 Stunden Zeit um eine Idee unter Zeitdruck in Code umzusetzen. Unterstützung bei der Ideenfindung und der Umsetzung erhältst Du von erfahrenen Mentoren unserer Partnerunternehmen. Ein Team besteht idealerweise aus Konzeptern, Programmierern und Webdesignern. Du kannst Dich als Team Log in: oder Dich vor Ort mit anderen zusammentun.</p> <p>Log in: <a href=',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1581321856000,
      duration: 7200000,
      id: '268599002',
      name: '111. JUG-München Treffen',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581526800000,
      local_date: '2020-02-12',
      local_time: '18:00',
      updated: 1581321959000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 25942014,
        name: 'Wirtshaus zum Isartal',
        lat: 48.112571716308594,
        lon: 11.553250312805176,
        repinned: true,
        address_1: 'Brudermühlstrasse 2',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1537211427000,
        name: 'Joomla User Group München',
        id: 29852639,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Joomla-User-Group-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Joomla-User-Group-Munchen/events/268599002/',
      description: '<p>Komm zum JUG-München Treffen und…</p> <p>- lerne nette Leute kennen, die sich mit Joomla! beschäftigen<br/>- tausche Dich in lockerer Umgebung beim Stammtisch mit Gleichgesinnten aus<br/>- erhalte Hilfe zur Selbsthilfe und stelle Fragen an andere User und Profis<br/>- höre Dir Vorträge über und rund um Joomla! an oder halte selbst welche<br/>- nimm an Workshops teil oder vielleicht magst Du selbst einen veranstalten?<br/>- teile Dein Wissen und Deine Erfahrungen mit Joomla! oder Erweiterungen<br/>- erfahre aktuelle Informationen aus erster Hand rund um Joomla! oder Joomla!-Events<br/>- profitiere von unseren tollen Lokations und melde Dich heute noch zum Treffen an</p> ',
      how_to_find_us: 'Nebenraum',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580404091000,
      duration: 7200000,
      id: '268323924',
      name: 'Adam Bien: From Java Developer to Web Guru in 1 hour - No slides',
      rsvp_limit: 120,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583254800000,
      local_date: '2020-03-03',
      local_time: '18:00',
      updated: 1580404091000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 101,
      venue: {
        id: 26112492,
        name: 'Google',
        lat: 48.14295959472656,
        lon: 11.54114818572998,
        repinned: false,
        address_1: 'Erika-Mann-Straße 33',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1565272185000,
        name: 'OpenValue München',
        id: 32563109,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'OpenValueMuenchen',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/OpenValueMuenchen/events/268323924/',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1580821390000,
      duration: 7200000,
      id: '268448587',
      name: 'Elementor MeetUp München - What the fuck is Crocoblock?',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583258400000,
      local_date: '2020-03-03',
      local_time: '19:00',
      updated: 1580837169000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 26638286,
        name: 'Heinrich Marketing GmbH',
        lat: 48.14986038208008,
        lon: 11.549469947814941,
        repinned: true,
        address_1: 'Nymphenburger Str. 58',
        address_2: 'Hinterhof, rechts',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1549966106000,
        name: 'Elementor München',
        id: 31146435,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Muenchen-Elementor-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Muenchen-Elementor-Meetup/events/268448587/',
      description: '<p>Crocoblock ist eine Suite von mittlerweile 17 Plugins der Ukrainischen Softwareschmiede Zemez. Crocoblock setzt auf Elementor auf und erweitert es mit einer Vielzahl an Widgets und Funktionalitäten, wie z.B. dynamische Darstellung von Inhalten, Mega Menü, visuelle Effekte, Style Manager, Filter- und Suchfunktionen, Addons für WooCommerce, Produktgalerien und vieles mehr.</p> <p>An einem Abend können wir nicht alle Möglichkeiten von Crocoblock darstellen, aber Helmut Göbel gibt ein Überblick und geht auf einige Widgets und Funktionen detaillierter ein.</p> <p>Dieses Meetup ist für jeden interessant, der keine 08/15-Webseite haben möchte, sondern in Design und/oder Funktion gerne etwas außergewöhnliches und überdurchschnittliches haben möchte.</p> <p>Hinweise:<br/>1. Wir sind zu Gast in der Agentur von Andreas Heinrich. Der Platz ist eingeschränkt. Deswegen bitte schnellstmöglich anmelden.<br/>2. Zum Netzwerken ist es sinnvoll, Visitenkarten mitzubringen und sich gegenseitig auszuhändigen. Das hilft, langfristig in Kontakt zu bleiben.<br/>3. In der Umgebung gibt es kaum Parkplätze. Es wird dringend empfohlen, den ÖPNV zu nutzen.</p> <p>Wir gehen anschließend in das Restaurant Trattoria Sankt Benno (Loristraße 14), wenige Schritte entfernt. Dort gibt es weiter Gelegenheit Fragen zu stellen und sich zum Thema Elementor auszutauschen. Wer mitkommen will, ist herzlich eingeladen.</p> ',
      how_to_find_us: 'Firma Heinrich Marketing befindet sich im Rückgebäude der Nymphenburger Str. 58, ca. 250 Meter von der U-Bahn-Station Maillinger Str. (U 1) entfernt. Es wird empfohlen, nicht mit dem Auto zu kommen. Freie Parkplätze gibt es in der Umgebung kaum.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1578482756000,
      duration: 10800000,
      id: '267744506',
      name: 'Das 1. Treffen der Agilluminaten 2020',
      rsvp_limit: 75,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581526800000,
      local_date: '2020-02-12',
      local_time: '18:00',
      updated: 1581498902000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 67,
      venue: {
        id: 26082467,
        name: 'codecentric AG',
        lat: 48.12557601928711,
        lon: 11.610230445861816,
        repinned: true,
        address_1: 'August-Everding-Str 20',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1533661901000,
        name: 'Agilluminaten',
        id: 29466316,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Agilluminaten',
        who: 'Agilluminaten',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Agilluminaten/events/267744506/',
      description: '<p>⭐️Der Einlass ist wegen der Anmeldung im Gebäude nur mit einem KOSTENLOSEN Eventbrite-Ticket möglich:',
      visibility: 'public',
      member_pay_fee: false
          },
        ],
      }

      export { mockEvents };