const mockEvents = {
    city: {
        id: 1007700,
        city: 'München',
        lat: 48.14,
        lon: 11.58,
        state: '',
        country: 'de',
        zip: 'meetup3',
        member_count: 1257
      },
      events: [
        {
          created: 1576845461000,
          duration: 7200000,
          id: '267317596',
          name: 'Pitch Club Developer Edition #47',
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1584039600000,
          local_date: '2020-03-12',
          local_time: '20:00',
          updated: 1576845613000,
          utc_offset: 3600000,
          waitlist_count: 0,
          yes_rsvp_count: 3,
          venue: {
            id: 25959917,
            name: 'Bar Ludwig II',
            lat: 48.12186813354492,
            lon: 11.58230972290039,
            repinned: true,
            address_1: 'Hochstraße 77',
            city: 'München',
            country: 'de',
            localized_country_name: 'Germany'
          },
          group: {
            created: 1539021073000,
            name: 'Pitch Club Developer Edition München',
            id: 30141555,
            join_mode: 'approval',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'Pitch-Club-Developer-Edition-Munchen',
            who: 'Mitglieder',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/267317596/',
          description: '<p>Softwareentwickler und IT-Professionals aufgepasst! Pitch Club veranstaltet am 12. März 2020 ab 17 Uhr in der Bar Ludwig II (Hochstraße 77, 81541 München) die “Pitch Club Developer Edition #47” in München. Hierfür suchen wir noch Entwickler und Projektmanager aus dem IT-Bereich, die an dem Event teilnehmen möchten.</p> <p>Beim Event treffen gestandene Unternehmen und Startups auf IT-Professionals, die es zu überzeugen gilt. Die Unternehmen pitchen ihr HR-Konzept, Jobs und Projekte und versuchen so, die Talente für sich zu gewinnen. Die Entwickler stellen zudem unbequeme Fragen und prüfen die Jobs auf Herz und Nieren. Am Ende müssen die Unternehmen in 1-on-1 Gesprächen nochmal alles geben, bei der alle Teilnehmer sich bei Speisen und Getränken austauschen und gegebenenfalls schon mit ihren zukünftigen Arbeitgebern in Kontakt treten können. Nach Abschluss der Veranstaltung geht das Event ab 20 Uhr in die öffentliche Afterwork Party über.</p> <p>Wenn Du an der kostenlosen Teilnahme (inklusive Snackbuffet, Softdrinks, Bier und Long Drinks) beim invite-only Event ab 17 Uhr interessiert bist, dann bewirb Dich unter:',
          visibility: 'public',
          member_pay_fee: false
        },
        {
          created: 1562151747000,
          duration: 169200000,
          id: '262837309',
          name: 'Campus Hackathon München 2020',
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1587142800000,
          local_date: '2020-04-17',
          local_time: '19:00',
          updated: 1562151747000,
          utc_offset: 7200000,
          waitlist_count: 0,
          yes_rsvp_count: 8,
          group: {
            created: 1501244830000,
            name: 'Tech_Hub München',
            id: 25186228,
            join_mode: 'open',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'Tech_Hub-Munchen',
            who: 'Members',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/Tech_Hub-Munchen/events/262837309/',
          description: '<p>At Campus Hackathon coders, creative developers and designers are working together intensively and under time-pressure hands-on projects. You have 24 hours to convert an idea into code. You already have some ideas? You want to use the tools and platforms you’re familiar with? No problem! The apps can be developed with the backends and frontend technologies you love. We’ll be providing healthy and tasty snacks and meals to keep your mind, body, soul balanced while hacking and you will be supported by experienced mentors of SAP, Finanz Informatik Solutions Plus and mindsquare. You can participate in a group or individually and we match you with another team.</p> <p>Beim Campus Hackathon hast Du 24 Stunden Zeit um eine Idee unter Zeitdruck in Code umzusetzen. Unterstützung bei der Ideenfindung und der Umsetzung erhältst Du von erfahrenen Mentoren unserer Partnerunternehmen. Ein Team besteht idealerweise aus Konzeptern, Programmierern und Webdesignern. Du kannst Dich als Team Log in: oder Dich vor Ort mit anderen zusammentun.</p> <p>Log in: ',
          visibility: 'public',
          member_pay_fee: false
        },
        {
          created: 1580404091000,
          duration: 7200000,
          id: '268323924',
          name: 'Adam Bien: From Java Developer to Web Guru in 1 hour - No slides',
          rsvp_limit: 120,
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1583254800000,
          local_date: '2020-03-03',
          local_time: '18:00',
          updated: 1580404091000,
          utc_offset: 3600000,
          waitlist_count: 0,
          yes_rsvp_count: 87,
          venue: {
            id: 26112492,
            name: 'Google',
            lat: 48.14295959472656,
            lon: 11.54114818572998,
            repinned: false,
            address_1: 'Erika-Mann-Straße 33',
            city: 'München',
            country: 'de',
            localized_country_name: 'Germany'
          },
          group: {
            created: 1565272185000,
            name: 'OpenValue München',
            id: 32563109,
            join_mode: 'open',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'OpenValueMuenchen',
            who: 'Members',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/OpenValueMuenchen/events/268323924/',
          description: '<p>Hello everybody! You\'ve been asking and here we\'re with another cool session!</p> <p>Adam Bien</p> <p>The longer you wait, the more JavaScript, CSS and Co. resemble ancient Java practices.<br/>Are you a Java developer without any web knowledge? Then you are also a WebGuru ...without knowing it.</p> <p>In this session, I will illustrate modern JavaScript, PWA, SPA, Offline Apps, Responsive Layout, Redux (...) technologies and APIs with (ancient) Java examples.</p> <p>Critical questions from the participants are more than welcome.</p> <p>Agenda</p> <p>18:00 Walk in<br/>18:30 Networking<br/>19:00 Talk<br/>20:00 Discussion<br/>20:30 Networking</p> <p>About the Speaker:</p>',
          visibility: 'public',
          pro_is_email_shared: false,
          member_pay_fee: false
        },
        {
          created: 1371224928000,
          duration: 7200000,
          id: 'drpzdgybcdbqb',
          name: 'Ruby User Group Meetup',
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1581530400000,
          local_date: '2020-02-12',
          local_time: '19:00',
          updated: 1579604167000,
          utc_offset: 3600000,
          waitlist_count: 0,
          yes_rsvp_count: 5,
          group: {
            created: 1370808069000,
            name: 'Munich Rubyshift, Ruby User Group',
            id: 8851722,
            join_mode: 'open',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'Munich-Rubyshift-Ruby-User-Group',
            who: 'Rubyists',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgybcdbqb/',
          description: '<p>🎤 Oliver Prater: Interacting with Kubernetes via Ruby</p> <p>We\'re actively searching for speakers! Want to become one? Ping us!</p> ',
          visibility: 'public',
          member_pay_fee: false
        },
        {
          created: 1580821390000,
          duration: 7200000,
          id: '268448587',
          name: 'Elementor MeetUp München - What the fuck is Crocoblock?',
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1583258400000,
          local_date: '2020-03-03',
          local_time: '19:00',
          updated: 1580837169000,
          utc_offset: 3600000,
          waitlist_count: 0,
          yes_rsvp_count: 4,
          venue: {
            id: 26638286,
            name: 'Heinrich Marketing GmbH',
            lat: 48.14986038208008,
            lon: 11.549469947814941,
            repinned: true,
            address_1: 'Nymphenburger Str. 58',
            address_2: 'Hinterhof, rechts',
            city: 'München',
            country: 'de',
            localized_country_name: 'Germany'
          },
          group: {
            created: 1549966106000,
            name: 'Elementor München',
            id: 31146435,
            join_mode: 'open',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'Muenchen-Elementor-Meetup',
            who: 'Mitglieder',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/Muenchen-Elementor-Meetup/events/268448587/',
          description: '<p>Crocoblock ist eine Suite von mittlerweile 17 Plugins der Ukrainischen Softwareschmiede Zemez. Crocoblock setzt auf Elementor auf und erweitert es mit einer Vielzahl an Widgets und Funktionalitäten, wie z.B. dynamische Darstellung von Inhalten, Mega Menü, visuelle Effekte, Style Manager, Filter- und Suchfunktionen, Addons für WooCommerce, Produktgalerien und vieles mehr.</p> <p>An einem Abend können wir nicht alle Möglichkeiten von Crocoblock darstellen, aber Helmut Göbel gibt ein Überblick und geht auf einige Widgets und Funktionen detaillierter ein.</p> <p>Dieses Meetup ist für jeden interessant, der keine 08/15-Webseite haben möchte, sondern in Design und/oder Funktion gerne etwas außergewöhnliches und überdurchschnittliches haben möchte.</p> <p>Hinweise:<br/>1. Wir sind zu Gast in der Agentur von Andreas Heinrich. Der Platz ist eingeschränkt. Deswegen bitte schnellstmöglich anmelden.<br/>2. Zum Netzwerken ist es sinnvoll, Visitenkarten mitzubringen und sich gegenseitig auszuhändigen. Das hilft, langfristig in Kontakt zu bleiben.<br/>3. In der Umgebung gibt es kaum Parkplätze. Es wird dringend empfohlen, den ÖPNV zu nutzen.</p> <p>Wir gehen anschließend in das Restaurant Trattoria Sankt Benno (Loristraße 14), wenige Schritte entfernt. Dort gibt es weiter Gelegenheit Fragen zu stellen und sich zum Thema Elementor auszutauschen. Wer mitkommen will, ist herzlich eingeladen.</p> ',
          how_to_find_us: 'Firma Heinrich Marketing befindet sich im Rückgebäude der Nymphenburger Str. 58, ca. 250 Meter von der U-Bahn-Station Maillinger Str. (U 1) entfernt. Es wird empfohlen, nicht mit dem Auto zu kommen. Freie Parkplätze gibt es in der Umgebung kaum.',
          visibility: 'public',
          pro_is_email_shared: false,
          member_pay_fee: false
        },
        {
          created: 1579249941000,
          duration: 10800000,
          id: '267986149',
          name: ' ObjektForum Special: Nexus Zoo - Kostenfreier Workshop',
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1581523200000,
          local_date: '2020-02-12',
          local_time: '17:00',
          updated: 1579250060000,
          utc_offset: 3600000,
          waitlist_count: 0,
          yes_rsvp_count: 10,
          venue: {
            id: 25713547,
            name: 'andrena objects Ag',
            lat: 48.12970733642578,
            lon: 11.538801193237305,
            repinned: false,
            address_1: 'Ganghoferstrasse 70',
            address_2: '5. Stock',
            city: 'München',
            country: 'de',
            localized_country_name: 'Germany'
          },
          group: {
            created: 1444904488000,
            name: 'ObjektForum München',
            id: 19029492,
            join_mode: 'open',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'ObjektForum-Munchen-Meetup',
            who: 'Mitglieder',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/ObjektForum-Munchen-Meetup/events/267986149/',
          description: '<p>Infos und Anmeldung unter<br/>',
          visibility: 'public',
          member_pay_fee: false
        },
        {
          created: 1578482756000,
          duration: 10800000,
          id: '267744506',
          name: 'Das 1. Treffen der Agilluminaten 2020',
          rsvp_limit: 80,
          date_in_series_pattern: false,
          status: 'upcoming',
          time: 1581526800000,
          local_date: '2020-02-12',
          local_time: '18:00',
          rsvp_close_offset: 'PT1H',
          updated: 1581067016000,
          utc_offset: 3600000,
          waitlist_count: 0,
          yes_rsvp_count: 67,
          venue: {
            id: 26082467,
            name: 'codecentric AG',
            lat: 48.12557601928711,
            lon: 11.610230445861816,
            repinned: true,
            address_1: 'August-Everding-Str 20',
            city: 'München',
            country: 'de',
            localized_country_name: 'Germany'
          },
          group: {
            created: 1533661901000,
            name: 'Agilluminaten',
            id: 29466316,
            join_mode: 'open',
            lat: 48.13999938964844,
            lon: 11.579999923706055,
            urlname: 'Agilluminaten',
            who: 'Agilluminaten',
            localized_location: 'München, Germany',
            state: '',
            country: 'de',
            region: 'en_US',
            timezone: 'Europe/Berlin'
          },
          link: 'https://www.meetup.com/Agilluminaten/events/267744506/',
          description: '<p>⭐️Der Einlass ist wegen der Anmeldung im Gebäude nur mit einem KOSTENLOSEN Eventbrite-Ticket möglich:',
          how_to_find_us: 'Die Veranstaltung findet in den Münchner Räumen der codecentric AG statt',
          visibility: 'public',
          member_pay_fee: false
          },
        ],
      }

      export { mockEvents };